server:
  port: 8083  # Change to 8081 for inventory-service, 8082 for payment-service

spring:
  application:
    name: order-service
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.otel.OtelAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: DEBUG

# OpenTelemetry exporter configuration
otel:
  tracing:
    exporter: zipkin
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans
